language: php

php:
  - '7.1'

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

before_script:
  - bin/naivechain&
  - bin/naivechain 1235 127.0.0.1:1234&

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)